### ISSUE TITLE
Battery not found on LenovoThinkPad T450

### ISSUE THREAD

**Issue by maurizio-emmex** [mrclksr/dsbbatmon#1]
Hi,
just installed NomadBSD where DSBBatmon is included.
From command line:
```
$ sudo dsbbatmon
Battery not present. Waiting ...
```
The battery info:
```
$ acpiconf -i 1
Design capacity:	71100 mWh
Last full capacity:	48780 mWh
Technology:		secondary (rechargeable)
Design voltage:		11220 mV
Capacity (warn):	2439 mWh
Capacity (low):		200 mWh
Low/warn granularity:	1 mWh
Warn/full granularity:	1 mWh
Model number:		45N1738
Serial number:		 1405
Type:			LION
OEM info:		LGC
State:			discharging
Remaining capacity:	57%
Remaining time:		3:45
Present rate:		7523 mW
Present voltage:	11522 mV
```

Thank you for your work.
Maurizio

**Comment by mrclksr** [comment]
Thank you for the feedback, Maurizio. The following commit should solve your problem: https://github.com/mrclksr/DSBBatmon/commit/fb0002d1ccbc25b34e982ba608b30549c018646d
Support for multiple batteries is yet to implement.

**Comment by maurizio-emmex** [comment]
Problem solved, thank you.
